name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: docker compose build

      - name: Run tests
        run: docker compose run --rm app python manage.py test

      - name: Lint
        run: docker compose run --rm app flake8
